### ISSUE TITLE
Support LDAP authentication

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/druid-operator#144]
As a user I'd like to use my existing [LDAP/AD](https://druid.apache.org/docs/latest/operations/auth-ldap.html) credentials to log into Druid. This was already done in e.g. [NiFi](https://github.com/stackabletech/nifi-operator/pull/303) or [Trino](https://github.com/stackabletech/trino-operator/pull/306). This can be especially helpful for writing tests. 

The LDAP support should be integrated in the structure from PR https://github.com/stackabletech/druid-operator/issues/6 which must be finished first. 
```
apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: druid
spec:
  version: 24.0.0-stackable0.1.0
  clusterConfig:
    tls:
      serverSecretClass: String # defaults to "tls"
      internalSecretClass: String # defaults to "tls"
    authentication: 
      - authenticationClass: druid-tls-authentication-class # String
      - authenticationClass: druid-ldap-authentication-class # String
```

This is done when
- [ ] LDAP is configurable in the CRD using the [LDAP structs](https://github.com/stackabletech/operator-rs/blob/main/src/commons/ldap.rs) from operator-rs
- [ ] A user/admin can configure Druid to use a LDAP server for authentication (while still offering existing authentication methods)
- [ ] There is documentation on how to configure Druid with LDAP using the Custom Resource
- [ ] Optional: There is an example demonstrating Druid with LDAP (docs, or example folder)
- There are tests which include:
  - [ ] OpenLDAP is installed and accessible via Druid
  - [ ] LDAP authenticated access to Druid works
- [ ] It is added to the feature tracker (ask Lars for help)

This depends on the reference architecture developed in https://github.com/stackabletech/issues/issues/170
