### ISSUE TITLE
Use HDFS ConfigMap to get a reference to the HDFS end-point for deep storage

### ISSUE THREAD

**Issue by adwk67** [stackabletech/druid-operator#188]
As a user of druid services I want to use the HDFS config-map to reference the HDFS endpoint for druid deep storage. Instead of:

```
  deepStorage:
    hdfs: 
      configMapName: production
      storageDirectory: /data
```

I want to use the hdfs config map and the properties contained in the "hdfs-site.xml" key therein.

This is done when
- the operator supports the CRD above
- the thing under `deepStorage` is a complex enum that can be extended to support more options later
- the hdfs-site and core-site from the referenced configMap are mounted in the classpath of druid as documented here: https://druid.apache.org/docs/latest/development/extensions-core/hdfs.html
