### ISSUE TITLE
Consolidate encryption, authentication and authorization

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/druid-operator#365]
Part of https://github.com/stackabletech/issues/issues/293
CRD:
```
apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: derby-druid
spec:
  image:
    productVersion: 24.0.0
    stackableVersion: 0.3.0
  clusterConfig:
    authentication:
      - authenticationClass: druid-tls-authentication-class (tls) # String
      - authenticationClass: druid-ldap-authentication-class (ldap) # String
    authorization:
      opa:
        configMapName: test-opa
        package: druid
    zookeeperConfigMapName: druid-znode
    metadataStorageDatabase:
      dbType: derby
      connString: jdbc:derby://localhost:1527/var/druid/metadata.db;create=true
      host: localhost
      port: 1527
    deepStorage:
      hdfs:
        configMapName: druid-hdfs
        directory: /druid
    tls:
      serverAndInternalSecretClass: secret_class # Option<String>. Defaults to "tls". We currently dont support different SecretClasses for clients and internal communication
```
